version: "3"
services:
    web:
        environment:
            VIRTUAL_HOST: woswormeileistung.marioslab.io
            LETSENCRYPT_HOST: woswormeileistung.marioslab.io
            LETSENCRYPT_EMAIL: badlogicgames@gmail.com
        networks:
            - reverse_proxy
networks:
    reverse_proxy:
        external:
            name: nginx-proxy
