version: "3"
services:
    web:
        image: nginx:alpine
        restart: always
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
            - ../html:/www
            - ./data/logs:/logs
        networks:
            - network

networks:
    network:
        driver: bridge
